import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { useEffect, useState } from "react"
import { withAuthPublic } from "utils/auth"

interface PageProps {
    user?: { accessToken: string }
}

const Home: NextPage<PageProps> = ({ user }) => {
    const [data, setData] = useState<any>({})
    useEffect(() => {
        if (user !== null) {
            console.log({ user })
            fetch(`https://api.github.com/graphql`, {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${user?.accessToken}`,
                },
                body: JSON.stringify({
                    query: `query {
                        viewer {
                            repositories(first:2, privacy: PRIVATE){
                                nodes {
                                    name
                                    isPrivate
                                }
                            }
                        }
                    }
                    
                    `,
                }),
            })
                .then((res) => res.json())
                .then((data) => setData(data))
                .catch((err) => console.error(err))
        }
    }, [user])

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                {user ? (
                    <div>
                        <pre>{JSON.stringify(user, null, 2)}</pre>
                        <pre>{JSON.stringify(data, null, 2)}</pre>
                    </div>
                ) : (
                    <div>
                        <Link href="/api/auth/signin">Login with Github</Link>
                    </div>
                )}
            </main>
        </div>
    )
}

export const getServerSideProps = withAuthPublic()

export default Home
