import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import { GitHub as GitHubIcon } from "react-feather"

const LandingPage: NextPage = () => {
    return (
        <div className="min-h-screen bg-gray-900 text-gray-100">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="max-w-xl mx-auto py-24 text-center flex flex-col items-center">
                    <h1 className="text-4xl font-black mb-6">
                        Shareable Link for your Private Repos
                    </h1>
                    <p className="text-gray-400 font-light">
                        Don&apos;t want to make your repo public but you still
                        want to share it with a group of people easily? We got
                        you! Connect your Github account and create a shareable
                        link to let people join your private repo.
                    </p>

                    <div className="mt-12">
                        <Link href="/api/auth/login">
                            <button className="bg-black text-white border border-gray-600 rounded py-2 px-8 flex items-center space-x-4">
                                <GitHubIcon size={14} />
                                <span>Login with Github</span>
                            </button>
                        </Link>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default LandingPage
